// window.addEventListener('load', function () {
var level1 = [
"obvious",
"discrete",
"colleagues",
"obsolete",
"operator precedence",
"precisely",
"deduction",
"trivial",
"arbitrary",
"guarantee",
"Apologies",
"hierarchy",
"centred ",
"environment",
"unfortunately",
"dilemma",
"necessarily",
"license (Verb) - I need to license this truck",
"licence (Noune) - Do you have a software licence ?",
"special concession",
"company's discretion",
"pretty awesome",
"sensible",
"scheduled ",
"guessing",
"preferable",
"maintenance",
"necessarily ",
"Authentication",
"consequences",
"catalogue",
"interprets",
"standardised ",
"immediately",
"anonymous",
"inadvertently",
"entirely plucked out"
];

var level0 = [
"individual",
"obvious",
"opinion",
"decided",
"distinct",
"discrete",
"appreciate",
"colleagues",
"timing",
"Customised",
"transition",
"convince",
"obsolete",
"operator precedence",
"commitment",
"admire",
"probably",
"certainly",
"uncertain",
"word sentence",
"suspect",
"precisely",
"investigated",
"cropped up",
"aiming",
"deduction",
"restrictions",
"inhibit - stop or block",
"recommended",
"acquire",
"transferring",
"available",
"Convenient",
"trivial - unimportant or insignificant",
"arbitrary",
"restricted",
"beautiful",
"Truly",
"dangerous",
"synchronous",
"mechanism",
"unnecessary",
"guarantee",
"Apologies",
"hierarchy",
"centred",
"environment",
"terrible",
"curious",
"conversation",
"business",
"apparently",
"concentrated ",
"favourably",
"unfortunately",
"despite",
"dilemma",
"necessarily",
"interim targets",
"clarification",
"concerned",
"reveal",
"naming convention",
"license (Verb) - I need to license this truck",
"licence (Noune) - Do you have a software licence ?",
"viable solution",
"surprised ",
"actually",
"opportunity",
"special concession",
"suggestions",
"company's discretion",
"procedure",
"confused",
"pretty awesome",
"deserves",
"familiar",
"performance",
"revenues",
"sensible",
"listeners",
"conversation",
"appreciate",
"successful",
"optimistic",
"exclusive",
"definitely",
"believe",
"scheduled",
"fantastic",
"credentials",
"instead ",
"guessing",
"continuous",
"seriously ",
"generous ",
"explicitly ",
"preferable",
"bothering everyone",
"maintenance",
"necessarily",
"Authentication",
"unpredictability",
"consequences",
"frequently",
"catalogue",
"decorates",
"relevant ",
"Apparently enough",
"indeed",
"interprets",
"standardised",
"apparently",
"immediately",
"ambiguity",
"anonymous ",
"inadvertently - accidentally",
"though - despite the fact that; although.",
"whether or not",
"screenshot",
"*****************************************************************************",
"entirely plucked out",
"it’s honourable idea",
"I have to admit",
"Thanks for letting us know",
"I have had a look into what is causing this and we appear to be receiving",
"Please accept my apologies for the inconvenience,",
"To correct a longstanding bit of confusion ",
"nothing amazes me any more",
"we are so skewed towards",
"I believe so yes",
"sorry, been sidetracked -- just need to finish something else off",
"---------------------------------------------",
"practice - Noun (Mostly used)",
"Handwriting practice was the first lesson of the day.",
"spelling practice",
"practise - Verb",
"I practised 7 days a week. (Tennis Player) ",
"--------------------------------------------",
"build 33 has/have the latest update. (has - correct)",
"i will have a look now."


];
// }); // window.addEventListener('load', function() {