// window.addEventListener('load', function () {
var level1 = [
"obvious",
"discrete",
"colleagues",
"obsolete",
"operator precedence",
"precisely",
"deduction",
"trivial",
"arbitrary",
"guarantee",
"Apologies",
"hierarchy",
"centred ",
"environment",
"unfortunately",
"dilemma",
"necessarily",
"license (Verb) - I need to license this truck",
"licence (Noun) - Do you have a software licence ?",
"special concession",
"company's discretion",
"pretty awesome",
"sensible",
"scheduled ",
"guessing",
"preferable",
"maintenance",
"necessarily ",
"Authentication",
"consequences",
"catalogue",
"interprets",
"standardized ",
"immediately",
"anonymous",
"inadvertently",
"entirely plucked out",
"cumulative",
"recognition",
"recursively",
"appropriate",
"quarter",
"higher",
"extension",
"decrypt",
"February",
"descendant ",
"succinct",
"swallow",
"shallow",
"liaison with",
"excerpt  - a short extract from a text.",
"subtleties - some exceptions",
"intuitive  - feels to be true even without conscious reasoning",
"consecutive",
"sieve  - Fine mesh(plastic/metal) for sifting(NOT shifting) fine FLOUR powder from  clumps.",
"strainer - Fine mesh(plastic/metal) strainer for sifting(NOT shifting) COFFEE.",
"sift - shaking (sifting the sieve to filter out the lumps in the flour)",
"squeezed",
"stick",
"timing",
"occurrence",
"ambiguous",
"synonyms",
"antonyms",
"anonymous",
"hiding",
"guaranteed ",
"triggered",
"Bad Practice",
"evaluates",
"existence",
"leverage = use",
"         = use (something) to maximum advantage;.",
" ex: the organization needs to leverage its key resources",
"trivial  = usual",
"Caveat "
];

var level0 = [
"individual",
"obvious",
"opinion",
"decided",
"distinct",
"discrete",
"appreciate",
"colleagues",
"timing",
"Customized",
"transition",
"convince",
"obsolete",
"operator precedence",
"commitment",
"admire",
"probably",
"certainly",
"uncertain",
"word sentence",
"suspect",
"precisely",
"investigated",
"cropped up",
"aiming",
"deduction",
"restrictions",
"inhibit - stop or block",
"recommended",
"acquire",
"transferring",
"available",
"Convenient",
"trivial - unimportant or insignificant",
"arbitrary",
"restricted",
"beautiful",
"Truly",
"dangerous",
"synchronous",
"mechanism",
"unnecessary",
"guarantee",
"Apologies",
"hierarchy",
"centred",
"environment",
"terrible",
"curious",
"conversation",
"business",
"apparently",
"concentrated ",
"favourably",
"unfortunately",
"despite",
"dilemma",
"necessarily",
"interim targets",
"clarification",
"concerned",
"reveal",
"naming convention",
"license (Verb) - I need to license this truck",
"licence (Noun) - Do you have a software licence ?",
"viable solution",
"surprised ",
"actually",
"opportunity",
"special concession",
"suggestions",
"company's discretion",
"procedure",
"confused",
"pretty awesome",
"deserves",
"familiar",
"performance",
"revenues",
"sensible",
"listeners",
"conversation",
"appreciate",
"successful",
"optimistic",
"exclusive",
"definitely",
"believe",
"scheduled",
"fantastic",
"credentials",
"instead ",
"guessing",
"continuous",
"seriously ",
"generous ",
"explicitly ",
"preferable",
"bothering everyone",
"maintenance",
"necessarily",
"Authentication",
"unpredictability",
"consequences",
"frequently",
"catalogue",
"decorates",
"relevant ",
"Apparently enough",
"indeed",
"interprets",
"standardized",
"apparently",
"immediately",
"ambiguity",
"anonymous ",
"inadvertently - accidentally",
"though - despite the fact that; although.",
"whether or not",
"screenshot",
"*****************************************************************************",
"entirely plucked out",
"it’s honorable idea",
"I have to admit",
"Thanks for letting us know",
"I have had a look into what is causing this and we appear to be receiving",
"Please accept my apologies for the inconvenience,",
"To correct a longstanding bit of confusion ",
"nothing amazes me any more",
"we are so skewed towards",
"I believe so yes",
"sorry, been sidetracked -- just need to finish something else off",
"---------------------------------------------",
"practice - Noun (Mostly used)",
"Handwriting practice was the first lesson of the day.",
"spelling practice",
"practise - Verb",
"I practised 7 days a week. (Tennis Player) ",
"--------------------------------------------",
"build 33 has/have the latest update. (has - correct)",
"i will have a look now.",
"---------------------------------------------",
"Once you are done",
"There will only ever be one instance",
"it is confusing as to which one is correct or best. ",
"this task hasn't been actioned due to unforeseen circumstances ",
"Has it been updated yet ?",
"Cheers for flagging it up mate!",
"I will get on to that this afternoon."
];
// }); // window.addEventListener('load', function() {